FROM tomcat:8

ADD setenv.sh /usr/local/tomcat/bin/
ADD battle-board-web.war /usr/local/tomcat/webapps/
ADD application.properties /usr/local/tomcat/properties/
ADD log4j.xml /usr/local/tomcat/properties/
